CREATE TABLE PUBLIC.TABLE1
(
    id      INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    number  INT
);

CREATE TABLE PUBLIC.table2
(
    id      INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    number  INT
);